on:
  push:
    tags:
      - v1.*
branches:
  only:
  - master
os: osx
language: objective-c
osx_image: xcode13.4
jobs:
  include:
    - stage: deploy      
      script: pod trunk push --allow-warnings
