if [[ -n $TRAVIS_TAG ]]; then
  # Travis does a shallow clone by default
  # so `master` is not present in the local metadata
  # in a build for another branch
  git fetch origin master:master   
  if ! (git branch --contains "$TRAVIS_TAG" | grep -qxE '. master'); then
    travis_terminate 0    # quit the build early
  fi
fi
os: osx
language: objective-c
osx_image: xcode13.4
jobs:
  include:
    - stage: deploy
      script: pod trunk push --allow-warnings
