#if [[ -n $TRAVIS_TAG ]]; then
#  git fetch origin master:master   
#  if ! (git branch --contains "$TRAVIS_TAG" | grep -qxE '. master-v2'); then
#    travis_terminate 0    # quit the build early
#  fi
#fi

os: osx
language: objective-c
osx_image: xcode13.4
jobs:
  include:
    - stage: "Tests"
      name: "Running Test Cases"
      script: 'xcodebuild test -project RudderTestingFramework.xcodeproj -scheme RudderTestingFrameworkTests -sdk iphonesimulator -destination "platform=iOS Simulator,OS=15.5,name=iPhone 13" ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO -skip-testing "RudderTestingFrameworkTests/RudderTestingFrameworkTests -skip-testing "RudderTestingFrameworkTests/RudderTestingFrameworkTests2" | xcpretty'
     - stage: deploy
       if: branch = master
       name: "Release to Cocoapods"
       script: pod trunk push --allow-warnings
