#if [[ -n $TRAVIS_TAG ]]; then
#  git fetch origin master:master   
#  if ! (git branch --contains "$TRAVIS_TAG" | grep -qxE '. master-v2'); then
#    travis_terminate 0    # quit the build early
#  fi
#fi
os: osx
language: objective-c
osx_image: xcode13.4
xcode_scheme: RudderTestingFrameworkTests
jobs:
  include:
    - stage: deploy
      script: pod trunk push --allow-warnings
